---
instance_id: [ID here]
mount_type: ebs
mount_dir: /data

aws_profile: default
aws_region: us-east-1

nfs_package: nfs-utils

efs_file_system_id: [ID here]

ebs_device: /dev/nvme1n1
ebs_fstype: xfs