---

- hosts: localhost
  tasks:
  - name: Write Inspec key to known hosts
    shell: "ssh-keyscan {{ groups['inspec'][0] }} >> /home/ec2-user/.ssh/known_hosts"

  - file:
      path: /home/ec2-user/.ssh/known_hosts
      owner: ec2-user
      group: ec2-user
      mode: 0644

- hosts: inspec

  vars_files:
    - ../vars/inspec_vars.yml

  pre_tasks:
    - include: ./common/wait-for-user-data.yml

  tasks:

    - name: Install common software requirements
      become: yes
      yum: name={{ item }} state=present
      with_items:
          - git
          - ansible

    - name: Copy Inspec files from s3
      shell: "aws s3 cp s3://daas-ansible-baba/agent.jar {{ inspec_path }}"

  roles:
    - { role: '../roles/wrapper/chefinspec', become: yes }
    - { role: '../roles/third_party/geerlingguy.java', become: yes }