---
- hosts: localhost
  vars_files:
    - ../vars/jenkins_vars.yml
    - "{{ jenkins_home }}/cfn_generated_vars.yml"
  tasks:
    - name: Get the Nexus password from the parameter store
      command: "aws ssm get-parameters --names NexusAdminPassword --with-decryption --region {{ aws_region }} --query \"Parameters[*].Value\" --output text"
      register: nexus_admin_password_result

    - name: Set the Nexus password
      set_fact: 
        nexus_admin_password: "{{ nexus_admin_password_result.stdout }}"

- hosts: demo-app
  vars:
    java_packages: java-1.8.0-openjdk
  roles:
    - { role: '../roles/third_party/geerlingguy.java', become: yes }
  post_tasks:
    - name: Store the nexus password as the nexus_admin_password
      set_fact:
        nexus_admin_password: "{{ hostvars['localhost']['nexus_admin_password'] }}"
    - name: Pull the latest jar from nexus
      maven_artifact:
        group_id: guru.springframework
        artifact_id: spring-boot-web
        extension: jar
        repository_url: "http://{{ nexus_ip }}:8081/repository/maven-snapshots"
        username: admin
        password: "{{ nexus_admin_password }}"
        dest: /home/ec2-user/springboot.jar
      become: yes

    - name: Deploy the jar to the instance
      shell: "(java -jar /home/ec2-user/springboot.jar >/dev/null 2>&1 &)"
      async: 10
      poll: 0
      become: yes