---

- hosts: fortify
  tasks:
    - name: fortify clean
      command: "sourceanalyzer -b simplebootwebapp -clean"
    - name: fortify set  
      command: "sourceanalyzer -b simplebootwebapp /var/fortify/Fortify/Samples/basic/eightball/EightBall.java"
    - name: fortify scan  
      command: "sourceanalyzer -b simplebootwebapp -scan -f simplebootwebapp.fpr"
    - name: create pdf  
      command: "ReportGenerator -format pdf -f fortify-scan.pdf -source simplebootwebapp.fpr"
    - name: push pdf to s3 
      command: "aws s3 cp fortify-scan.pdf s3://daas-fortify-installer/fortify-scan.pdf"