---
# This is an example playbook to execute inspec tests.

- name: Transfer and execute a Inspec script.
  hosts: localhost
  become: yes
  vars:
    inspec_test_directory: "/home/ec2-user/jenkins/Source"

  tasks:

    - name: Create Molecule directory for test files
      file:
        path: "{{ inspec_test_directory }}"
        state: directory

    # - name: Copy Inspec tests to remote
    #   copy:
    #     src: "{{ item }}"
    #     dest: "{{ inspec_test_directory }}/{{ item | basename }}"
    #   with_fileglob:
    #     - "{{ playbook_dir }}/tests/test_*.rb"

    - name: Create chefinspec test file
      template:
        src: ../templates/test_inspec.rb.j2
        dest: "{{ inspec_test_directory }}/test_inspec.rb"
        owner: ec2-user
        group: ec2-user
        mode: 0640   

    - name: Register test files
      shell: "ls {{ inspec_test_directory }}/test_*.rb"
      register: test_files

    - name: Execute Inspec tests
      #command: "inspec exec {{ item }} --no-color --reporter progress"
      command: "inspec exec {{ item }} --reporter html:inspec.html"      
      # register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      when: RUN_APP_SCAN
      ignore_errors: true

    - name: Execute Inspec tests from Github inspec Compliance
      command: "inspec exec https://github.com/chris-rock/acme-inspec-profile.git --reporter html:inspec.html"
      register: profile_results
      when: RUN_OS_SCAN
      ignore_errors: true