---

- hosts: localhost
  tasks:
  - name: Write Sonar key to known hosts
    shell: "ssh-keyscan {{ groups['sonar'][0] }} >> /home/ec2-user/.ssh/known_hosts"
    become: yes

  - name: Change permisions
    file:
      path: /home/ec2-user/.ssh/known_hosts
      owner: ec2-user
      group: ec2-user
      mode: 0644
    become: yes

- hosts: sonar
  vars_files:
    - ../vars/sonar_vars.yml
    - "/var/lib/jenkins/cfn_generated_vars.yml"
  pre_tasks:
    - name: Ensure sonar group exists
      group:
        name: "{{ sonar_group }}"
        state: present
      become: yes
      when: sonar_ebs_creation

    - name: Ensure sonar user exists
      user:
        name: "{{ sonar_user }}"
        group: "{{ sonar_group }}"
      become: yes
      when: sonar_ebs_creation

    - name: Ensure sonar data dir exists for EBS
      file:
        path: /sonar-ebs/sonar
        state: directory
        owner: "{{ sonar_user }}"
        group: "{{ sonar_group }}"
        recurse: yes
      become: yes
      when: sonar_ebs_creation

    - name: Ensure mysql group exists
      group:
        name: mysql
        state: present
      become: yes
      when: sonar_ebs_creation

    - name: Ensure mysql user exists
      user:
        name: mysql
        group: mysql
      become: yes
      when: sonar_ebs_creation

    - name: Ensure mysql_datadir /sonar-ebs/mysql exists for EBS
      file:
        path: /sonar-ebs/mysql
        state: directory
        owner: mysql
        group: mysql
        recurse: yes
        mode: 0755
      become: yes
      when: sonar_ebs_creation

    - include: ./common/wait-for-user-data.yml
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present
        disable_gpg_check: yes
      when: ansible_os_family == "RedHat"
      become: yes

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
  roles:
    - { role: '../roles/third_party/geerlingguy.java', become: yes }
    - { role: '../roles/third_party/geerlingguy.mysql', become: yes }
    - { role: '../roles/third_party/ansible-role-sonar-master', become: yes }
